---
title: "PROseq analysis"
author: "Johan"
date: "10/25/2019"
output: html_document

params:
  workingDir: /Users/johanreimegard/git/flyEmbryogenesis
  RscriptsDir: R_Analysis/Rscripts  
  dataDir: data/PROseq
  
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
```

# PROseq analysis.


```{r idxstats}

idxDataDir = paste(params$workingDir, params$dataDir,"idxstats", sep = "/")
files = list.files(path = idxDataDir)

idxstats = read.table(file = paste(idxDataDir, files[1] ,sep = "/"), header = F, sep = "\t")
sampleName = gsub(pattern = ".dmel.bowtie2.idxstats.txt", replacement = "", x = files[1])
colnames(idxstats) = c("chromosome","Length",sampleName,"unmapped_reads" )
idxstats = idxstats %>% select("chromosome","Length",sampleName)
  

for(i in 2: length(files)){
  df = read.table(file = paste(idxDataDir, files[i] ,sep = "/"), header = F, sep = "\t")
  sampleName = gsub(pattern = ".dmel.bowtie2.idxstats.txt", replacement = "", x = files[i])
  colnames(df) = c("chromosome","Length",sampleName,"unmapped_reads" )
  df = df %>% select("chromosome","Length",sampleName)
  idxstats = inner_join(idxstats,df)
}

idxstatsDF = idxstats %>% gather(key = sample,value = counts ,-chromosome,-Length )

idxstatsDF$species = "Mouse"
idxstatsDF$species[grep(pattern = "chr",x = idxstatsDF$chromosome)] = "Drosophila"



#ggplot(idxstatsDF, aes (x = sample, y = counts, fill = species, color = chromosome)) +geom_col(position = "fill")+ coord_flip() +
 #theme(legend.position = "top")


class(idxstatsDF$Length)

idxstatsDF$Length = as.numeric(idxstatsDF$Length)
idxstatsDF$counts = as.numeric(idxstatsDF$counts)
idxSummary = idxstatsDF %>% 
  dplyr::select(Length,sample,counts,species) %>%
  dplyr::group_by(species, sample) %>%
  dplyr::summarize(n(), TotalCount = sum(counts), TotalLength = sum(Length), relativeCount = TotalCount/ TotalLength )


# Plot absolute counts between Droshphila and Mouse
ggplot(idxSummary, aes (x = sample, y = TotalCount, fill = species, color = )) +geom_col(position = "fill")+ coord_flip() +
 theme(legend.position = "top")

ggsave("PROseq_counts_distribution.pdf")

# Plot relative counts based on genome size between Droshphila and Mouse
ggplot(idxSummary, aes (x = sample, y = relativeCount, fill = species)) +geom_col(position = "fill")+
  coord_flip() + theme(legend.position = "top")

ggsave("PROseq_counts_relative_distribution.pdf")

```

