---
title: "k means clustering"
author: "Jenny Jakobsson"
date: "11/12/2020"
output: html_document

params:
    workingDir: ~/Applied_Bioinformatics_Group_4
    annotationDir: data_johan/annotations
    proSeqDir: data_johan/results/PROseq
    proSeq.data: PROseq.data.tsv
    proSeq.data.PPC: PROseq.data.PPC.tsv
    ATACSeqDir: data_johan/results/ATACseq
    ATACSeq.data: ATACseq.data.raw.tsv
    chipSeqDir: data_johan/results/chipSeq
    k27ac.data: K27ac.ChIPseq.peak.pattern.raw.tsv
    CBP.data: ATAC-CBP_dm6.ChIPseq.peak.pattern.raw.tsv
    RscriptsDir: script/original_scripts
    dataDir: data_johan/data/ATACseq
    sampleInfo: data_johan/information/ChIP_ATAC_sampleInfo.tab.txt
    count_ATAC: ATAC.peak.featureCount.count.tab.txt 
    bestTargets: data_johan/information/all/TopTargets.txt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#BiocManager::install("clusterProfiler")
#BiocManager::install("org.Dm.eg.db")
#install.packages("ggrepel")
#install.packages("kableExtra")
#install.packages("heatmap3")
#install.packages("tsne")
#install.packages("umap")
library(umap)
library(clusterProfiler)
library(org.Dm.eg.db)
library(tidyverse)
library(gplots)
library(knitr)
library(kableExtra)
library("viridis")     
library(heatmap3)
library(ggrepel)
library(tsne)
```

```{r  add  transcript to gene Information}

# Loading the gtf file to extract annotation. 
gtfFile = paste(params$workingDir, "Drosophila_melanogaster.BDGP6.28.101.gtf", sep = "/")
gtfInfo = read.table(file = gtfFile, header = F, sep = "\t", quote = "", stringsAsFactors = F)
# Chosing only the annotation for genes
gtfInfoGene = gtfInfo %>% dplyr::filter(V3 == "gene")
# Extract only gene name and geneID
gtfInfoGene = gtfInfoGene[grep(pattern = "gene_biotype \"protein_coding\"",x = gtfInfoGene$V9 ),  ] 
gtfInfoGene= gtfInfoGene %>% separate(col = V9,sep = ";",into =  c("geneID1", "geneName1", "gene_source", "gene_biotype", "empty"))
gtfInfoGene= gtfInfoGene %>% separate(col = geneID1,sep = "\"",into =  c("irrelevant", "geneID", "empty"))
gtfInfoGene= gtfInfoGene %>% separate(col = geneName1,sep = "\"",into =  c("irrelevant1", "geneName", "empty"))
#gtfInfoGene = gtfInfoGene$geneID

###### Contiune to fix the data frame gtfInfoGene
gtfInfoAnnotation = gtfInfoGene  %>% select(V1,V4,V5,V7,geneID,geneName)

# Summerize the information in a table with Chr, start, stop, direction, 
PROseqGenes = gtfInfoAnnotation %>% dplyr::rename("Chr"= V1, "GeneStart" = V4,"GeneStop" = V5,"geneDir" = V7)
PROseqGenes$Chr = paste ("chr",PROseqGenes$Chr, sep ="")

#Extract RNA information
gtfInfomRNA = gtfInfo %>% dplyr::filter(V3 == "transcript")
#Extract geneID and transcriptID
gtfInfomRNA = gtfInfomRNA[grep(pattern = "gene_biotype \"protein_coding\"",x = gtfInfomRNA$V9 ),  ] 
gtfInfomRNA_DF= gtfInfomRNA %>% separate(col = V9,sep = ";",into =  c("geneID1", "transcriptID1"))
gtfInfomRNA_DF= gtfInfomRNA_DF %>% separate(col = geneID1,sep = "\"",into =  c("irrelevant", "geneID"))
gtfInfomRNA_DF= gtfInfomRNA_DF %>% separate(col = transcriptID1,sep = "\"",into =  c("irrelevant1", "transcriptID"))
gene2transcriptInfo  = gtfInfomRNA_DF %>% dplyr::select(geneID,transcriptID)

```

## PRO seq

### CDS values
```{r PROseq  CDS info}
PROseqInfo = read.table( file = paste( params$workingDir, params$proSeqDir, params$proSeq.data,
                          sep = "/"),
                         quote = "", sep = "\t", 
                         header = TRUE, stringsAsFactors = F) 

annotation2 =  PROseqInfo %>% filter(factor %in% c("Toll10b","Toll9","Gd7") & annotation2 == "DE") %>%
  dplyr::select(geneID, annotation, distance, factor, direction ) %>%
  distinct()


PROseqData = PROseqInfo %>% dplyr::select(geneID,factor, direction, annotation,annotation2, Time, Gd7,Toll10b,Toll9) %>% distinct()


colnames(PROseqData)[6] = paste("PROseq", colnames(PROseqData)[6], sep = "_")
colnames(PROseqData)[7] = paste("PROseq", colnames(PROseqData)[7], sep = "_")
colnames(PROseqData)[8] = paste("PROseq", colnames(PROseqData)[8], sep = "_")
colnames(PROseqData)[9] = paste("PROseq", colnames(PROseqData)[9], sep = "_")


PROseqData.DE  = PROseqData %>% filter(annotation2 == "DE" & factor != "Time" ) 
PROseqData.best = PROseqData %>% filter(annotation == "Literature & Roshan & This") 
PROseqData.best = inner_join(PROseqData.best, gtfInfoAnnotation) 
PROseqData.best = PROseqData.best %>% dplyr::select(geneID, geneName)

topTargetsFileName = paste(params$workingDir, params$bestTargets, sep = "/")
topTarget = read.table(file = topTargetsFileName, header = T, sep = "\t", 
                       quote = "", stringsAsFactors = F)

topTarget = inner_join(topTarget,gtfInfoAnnotation ) 


PROseqData.topTargets =  inner_join(PROseqData,topTarget) %>% dplyr::select(geneName, factor, direction, annotation, Factor, Direction )


write.table(x = PROseqData.topTargets, file = topTargetsFileName,sep = "\t", quote = F, row.names = F, col.names =  T)


PROseqInfo %>% dplyr::select(geneID,Chr,Start,End,Strand,factor, direction, annotation,annotation2,Gd7,Toll9) %>% distinct()  %>%  filter( factor != "Time") %>% ggplot(mapping = aes(x = Gd7, y = Toll9, color = factor, shape = direction )) + geom_point() 


# ChIPseq analysisdi
```


### PPC values

```{r  PROseq  PPS info}



PROseqInfo.PPC = read.table( file = paste( params$workingDir, params$proSeqDir, params$proSeq.data.PPC,
                          sep = "/"),
                         quote = "", sep = "\t", 
                         header = TRUE, stringsAsFactors = F) 


PROseqData.DE.PPC = left_join(PROseqData.DE, PROseqInfo.PPC)


# ChIPseq analysisdi
```





## ATAC seq

```{r ATACseq annotation}



ATACseqInfo = read.table( file = paste( params$workingDir, params$ATACSeqDir, params$ATACSeq.data,
                          sep = "/"),
                         quote = "", sep = "\t", 
                         header = TRUE, stringsAsFactors = F) 




ATACseqInfo = ATACseqInfo %>% dplyr::select(Geneid, factor, direction, Time,Gd7,  Toll10b,Toll9,)
colnames(ATACseqInfo) = paste("ATACseq", colnames(ATACseqInfo), sep = "_")

# PRO_ATAC = left_join(PROseqData.DE.PPC, ATACseqInfo)
# PRO_ATAC[is.na(PRO_ATAC)] = 0
# PRO_ATAC$ATAC_region[PRO_ATAC$ATAC_region == 0] = "No_region"
# PRO_ATAC$ATAC_factor[PRO_ATAC$ATAC_factor == 0] = "No_factor"
# PRO_ATAC$ATAC_direction[PRO_ATAC$ATAC_direction == 0] = "None"
# 
# 
# 
# PRO_ATAC_CHiP[is.na(PRO_ATAC_CHiP)] = 0
# PRO_ATAC_CHiP$K27ac_region[PRO_ATAC_CHiP$K27ac_region == 0] = "No_region"
# PRO_ATAC_CHiP$K27ac_factor[PRO_ATAC_CHiP$K27ac_factor == 0] = "None"
# PRO_ATAC_CHiP$K27ac_direction[PRO_ATAC_CHiP$K27ac_direction == 0] = "None"

# 
# 
# PRO_ATAC_CHiP[is.na(PRO_ATAC_CHiP)] = 0
# PRO_ATAC_CHiP$CBP_region[PRO_ATAC_CHiP$CBP_region == 0] = "No_region"
# PRO_ATAC_CHiP$CBP_factor[PRO_ATAC_CHiP$CBP_factor == 0] = "None"
# PRO_ATAC_CHiP$CBP_direction[PRO_ATAC_CHiP$CBP_direction == 0] = "None"
# 





# ChIPseq analysisdi
```

## K27ac seq



```{r K27ac annotation}





K27acInfo =  read.table( file = paste( params$workingDir, params$chipSeqDir,
                                        params$k27ac.data,
                          sep = "/"),
                         quote = "", sep = "\t", 
                         header = TRUE, stringsAsFactors = F)


K27acLocation = K27acInfo %>% dplyr::select(Geneid, Chr, Start,End,  Strand)

K27acInfo = K27acInfo %>% dplyr::select(Geneid, factor, direction,Gd7,  Toll10b,Toll9,)
colnames(K27acInfo) = paste("K27ac", colnames(K27acInfo), sep = "_")

colnames(K27acLocation) = paste("K27ac", colnames(K27acLocation), sep = "_")

colnames(K27acLocation)[2] = "Chr"

```


## CBP seq

```{r H annotation}

CBPInfo =  read.table( file = paste( params$workingDir, params$chipSeqDir, params$CBP.data, sep = "/"),
                         quote = "", sep = "\t", 
                         header = TRUE, stringsAsFactors = F) 

CBPLocation = CBPInfo %>% dplyr::select(Geneid, Chr, Start,End,  Strand)
CBPInfo = CBPInfo %>% dplyr::select(Geneid, factor, direction,Gd7,  Toll10b,Toll9,)
colnames(CBPInfo)[2:ncol(CBPInfo)] = paste("CBP", colnames(CBPInfo)[2:ncol(CBPInfo)], sep = "_")
colnames(CBPInfo)[1] = paste("ATACseq", colnames(CBPInfo)[1], sep = "_")

ATAC_CHiP = inner_join(ATACseqInfo, CBPInfo )
colnames(CBPLocation) = paste("ATACseq", colnames(CBPLocation), sep = "_")
colnames(CBPLocation)[2] = "Chr"
```


```{r merge with annotation}
usedRegionsAndGenes = read.table(file = paste(params$workingDir, "data_johan/results/combined.peaks.location.tsv" ,sep = "/"),header = T, quote = "", sep = "\t",stringsAsFactors = F)
colnames(usedRegionsAndGenes)[1] = "ATACseq_Geneid"
AllData = inner_join(ATAC_CHiP, usedRegionsAndGenes)
AllData = inner_join(AllData, K27acInfo) 
AllData = AllData %>% distinct()

AllData =inner_join(PROseqData.DE.PPC, AllData)

AllData = AllData %>% mutate(Enhancer_Gd7 =  ATACseq_Gd7 +CBP_Gd7 + K27ac_Gd7)
AllData = AllData %>% mutate(Enhancer_Toll10b =  ATACseq_Toll10b +CBP_Toll10b + K27ac_Toll10b)
AllData = AllData %>% mutate(Enhancer_Toll9 =  ATACseq_Toll9 + CBP_Toll9 + K27ac_Toll9)

```

# Merge all the data.

## Fix the names into readable genes
```{r  annotate the loadings scores  }

universe <- bitr(unique(AllData$geneID), fromType = "ENSEMBL",
                 toType = c("SYMBOL"),
                 OrgDb = org.Dm.eg.db)

universe  =  universe %>% dplyr::rename( geneID = ENSEMBL )

AllData = inner_join(AllData, universe) 
AllData$SYMBOL_unique = make.names(AllData$SYMBOL, unique = TRUE)
```


## Fix the data so that it can be analysed


```{r merge all the data}

PRO_ATAC_CHiP_data = AllData %>%
  group_by(SYMBOL, factor, direction,annotation) %>%
  summarise(PROseq_Time = mean(PROseq_Time), PROseq_Gd7 = mean(PROseq_Gd7), PROseq_Toll10b = mean(PROseq_Toll10b),PROseq_Toll9 = mean(PROseq_Toll9),
            PPC_Time = mean(PPC_Time), PPC_Gd7 = mean(PPC_Gd7), PPC_Toll10b = mean(PPC_Toll10b),PPC_Toll9 = mean(PPC_Toll9),
            ATACseq_Time = mean(ATACseq_Time), ATACseq_Gd7 = mean(ATACseq_Gd7), ATACseq_Toll10b = mean(ATACseq_Toll10b),  ATACseq_Toll9 = mean(ATACseq_Toll9),
           K27ac_Gd7 = mean(K27ac_Gd7), K27ac_Toll10b = mean(K27ac_Toll10b),  K27ac_Toll9 = mean(K27ac_Toll9),
             CBP_Gd7 = mean(CBP_Gd7), CBP_Toll10b = mean(CBP_Toll10b),  CBP_Toll9 = mean(CBP_Toll9))


AllData = AllData %>% dplyr::select(SYMBOL,SYMBOL_unique,geneID,annotation ,factor,direction,
                             PPC_factor,PPC_direction,
                             ATACseq_Geneid,ATACseq_factor,ATACseq_direction,
                             CBP_factor,CBP_direction,
                             K27ac_Geneid,K27ac_factor,K27ac_direction,
                             PROseq_Time,PROseq_Gd7,PROseq_Toll10b,PROseq_Toll9,
                             PPC_Time,PPC_Gd7,PPC_Toll10b,PPC_Toll9,
                             ATACseq_Time,ATACseq_Gd7,ATACseq_Toll10b,ATACseq_Toll9,
                             CBP_Gd7,CBP_Toll10b,CBP_Toll9,
                             K27ac_Gd7,K27ac_Toll10b,K27ac_Toll9,
                             Enhancer_Gd7,Enhancer_Toll10b,Enhancer_Toll9)
AllData2 = AllData%>% dplyr::select(
                             PROseq_Time,PROseq_Gd7,PROseq_Toll10b,PROseq_Toll9,
                             PPC_Time,PPC_Gd7,PPC_Toll10b,PPC_Toll9,
                             ATACseq_Time,ATACseq_Gd7,ATACseq_Toll10b,ATACseq_Toll9,
                             CBP_Gd7,CBP_Toll10b,CBP_Toll9,
                             K27ac_Gd7,K27ac_Toll10b,K27ac_Toll9)

AllData3 = AllData%>% dplyr::select(
                             PROseq_Time,PROseq_Gd7,PROseq_Toll10b,PROseq_Toll9,
                             PPC_Time,PPC_Gd7,PPC_Toll10b,PPC_Toll9,
                             ATACseq_Time,ATACseq_Gd7,ATACseq_Toll10b,ATACseq_Toll9,
                             CBP_Gd7,CBP_Toll10b,CBP_Toll9,
                             K27ac_Gd7,K27ac_Toll10b,K27ac_Toll9)

AllData.saved = AllData

```


## Check with PCA 

```{r PCA}

PRO_ATAC_CHiP_data2 = as.data.frame( AllData%>% dplyr::select(
                             PROseq_Time,PROseq_Gd7,PROseq_Toll10b,PROseq_Toll9,
                             PPC_Time,PPC_Gd7,PPC_Toll10b,PPC_Toll9,
                             ATACseq_Time,ATACseq_Gd7,ATACseq_Toll10b,ATACseq_Toll9,
                             CBP_Gd7,CBP_Toll10b,CBP_Toll9,
                             K27ac_Gd7,K27ac_Toll10b,K27ac_Toll9))
PRO_ATAC_CHiP_data2 = as.data.frame( AllData%>% dplyr::select(
                             PROseq_Gd7,PROseq_Toll10b,PROseq_Toll9,
                             Enhancer_Gd7,Enhancer_Toll10b,Enhancer_Toll9))


rownames(PRO_ATAC_CHiP_data2) = AllData$SYMBOL_unique

mir.pca <- prcomp(PRO_ATAC_CHiP_data2, center = TRUE, scale = FALSE) 
e.var = (mir.pca[['sdev']]^2 / sum(mir.pca[['sdev']]^2))
e.var = as.data.frame( e.var )
e.var$PC = as.factor(1:nrow(e.var)) 
e.var$Variance = e.var$e.var*100
e.var$CumulativeVariance = cumsum(e.var$Variance)
qplot(PC, Variance, data=e.var, geom = c("point")
      , ylim = c(0,max(e.var$Variance)+5) 
      ,ylab = "Variance (%)")


pctable = as.data.frame(mir.pca$x)[, 1:4]
pctable$SYMBOL_unique = rownames(pctable)
AllData = inner_join(AllData, pctable)

ggplot(data = AllData, mapping = aes(x = PC1, y = PC2 ,color = K27ac_factor , shape = K27ac_direction, label = SYMBOL))+ geom_point()

ggplot(data = AllData, mapping = aes(x = PC1, y = PC2 ,color = factor , shape = direction, label = SYMBOL))+ geom_point()


ggplot(data = AllData, mapping = aes(x = PC3, y = PC4 ,color = K27ac_factor , shape = K27ac_direction, label = SYMBOL))+ geom_point()

ggplot(data = AllData, mapping = aes(x = PC3, y = PC4 ,color = factor , shape = direction, label = SYMBOL))+ geom_point()

```


# Save the data

```{r save the data}
write.table(x = AllData,
            file = paste(params$workingDir,"results/original_method/combined.AllData.withMetaData.txt" ,sep = "/"),
        quote = F,
        sep = "\t",
        row.names = F,
        col.names = T
)


```



