---
title: "Implementing UMAP"
author: "Elin Antonsson"
date: "11/25/2020"
output: html_document
---

# all_enhancer.data = allEnhancerInfo2[, grep("ATAC|PRO|CBP|K27ac", colnames(allEnhancerInfo2))]
# all_enhancer.labels = allEnhancerInfo2[, c("ATAC", "PRO", "CBP", "K27ac")]

# allEnhancerInfo2.umap = umap(all_enhancer.data)
# head(allEnhancerInfo2.umap$layout, 3)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("devtools")
devtools::install_github("ropenscilabs/umapr")
library(umapr)
library(tidyverse)
```

## R Markdown

```{r Trying UMAPR, filter after, better}
all_enhancer.data = allEnhancerInfo2[, grep("ATAC|PRO|CBP|K27ac", colnames(allEnhancerInfo2))]
embedding <- umap(all_enhancer.data)
new_embedding = left_join(EnhancerInfo,embedding)

head(new_embedding)

#I think it is best not to filter
#new_embedding = new_embedding %>% filter(!is.na(enhancerGenotype))

new_embedding %>% 
  mutate(Species = new_embedding$enhancerGenotype) %>%
  ggplot(aes(UMAP1, UMAP2, color = Species)) + geom_point()

#Plot a shiny graph
run_umap_shiny(new_embedding)

# Plot density plot
FE =  AllData %>% filter(enhancer == 1) %>% ggplot(aes(UMAP1, UMAP2, color = enhancerGenotype )) + geom_point()+ geom_density_2d(AllData,mapping = aes(UMAP1, UMAP2), color= "grey")
FI =  AllData %>% filter(inSitu == 1) %>% ggplot(aes(UMAP1, UMAP2, color = inSituLocation )) + geom_point()+ geom_density_2d(AllData,mapping = aes(UMAP1, UMAP2), color= "grey")

FE + FI+ plot_layout(ncol = 1)

```

## Filter before UMAP instead of after

```{r filter before}
allEnhancerInfoWithInfo = left_join(EnhancerInfo,allEnhancerInfo2)

new_embedding = allEnhancerInfoWithInfo %>% filter(!is.na(enhancerGenotype))

all_enhancer.data = new_embedding[, grep("ATAC_Gd7|ATAC_Time|ATAC_Toll10b|ATAC_Toll9|PRO_Gd7|PRO_Toll10b|PRO_Toll9|PRO_Time|CBP_Gd7|CBP_Toll10b|CBP_Toll9|K27ac_Gd7|K27ac_Toll10b|K27ac_Toll9", colnames(new_embedding))]
all_enhancer.labels = new_embedding[, "enhancerGenotype"]


embedding <- umap(all_enhancer.data)

head(embedding)


FE =  embedding %>% filter(enhancer == 1) %>% ggplot(aes(UMAP1, UMAP2, color = enhancerGenotype )) + geom_point()+ geom_density_2d(AllData,mapping = aes(UMAP1, UMAP2), color= "grey")
FI =  embedding %>% filter(inSitu == 1) %>% ggplot(aes(UMAP1, UMAP2, color = inSituLocation )) + geom_point()+ geom_density_2d(AllData,mapping = aes(UMAP1, UMAP2), color= "grey")

FE + FI+ plot_layout(ncol = 1)


embedding %>% 
  mutate(Species = all_enhancer.labels) %>%
  ggplot(aes(UMAP1, UMAP2, color = Species)) + geom_point()

run_umap_shiny(new_embedding)

```

```{r clustering}

standard_embedding = umap.UMAP(random_state=42).fit_transform(all_enhancer.data)


clusterable_embedding = umap(
    n_neighbors=30,
    min_dist=0.0,
    n_components=2,
    random_state=42,
#fit_transform(data.matrix(all_enhancer.data), model))

#plt.scatter(embedding, clusterable_embedding[, 1],
            c=mnist.target, s=0.1, cmap='Spectral');

```

```{r ROC}
AllData = embedding %>% mutate(distance1 = abs(UMAP1))
AllData = AllData %>% mutate(distance2 = (UMAP1^2+UMAP2^2)^0.5)


d1ROCi = getROCinfo(AllData,scoreColumn = "distance1", classColumn = "inSitu")
d2ROCi = getROCinfo(AllData,scoreColumn = "distance2", classColumn = "inSitu")
d1ROCe = getROCinfo(AllData,scoreColumn = "distance1", classColumn = "enhancer")
d2ROCe = getROCinfo(AllData,scoreColumn = "distance2", classColumn = "enhancer")

ROCplotInfo = rbind (d1ROCi$ROCplotInfo, d2ROCi$ROCplotInfo,
                     d1ROCe$ROCplotInfo, d2ROCe$ROCplotInfo)
ROCplotSummary = rbind(d1ROCi$Youden, d2ROCi$Youden,
                     d1ROCe$Youden, d2ROCe$Youden)

ggplot(ROCplotInfo, mapping =  aes(x = FPR, y = TPR, color = score))+
  geom_line()+
  geom_abline()+
  geom_point(data = ROCplotSummary, mapping = aes(y = TPR, x = FPR, color = score ), size = 4) +
    facet_grid(.~classifier)
```

```{r ROC}
custom.config = umap.defaults
custom.config$n_components = 5


umap <- umap(all_enhancer.data, config=custom.config)

df <- data.frame(x = umap$layout[,1],
                 y = umap$layout[,2],
                 Species = colnames(all_enhancer.data))

ggplot(df, aes(x, y, colour = Species)) +
  geom_point()

```

