f=open("output/gene_expr.txt","r")
next(f)
Gd7_3h=open("output/Gd7_3h_expr.txt","w")
Gd7_5h=open("output/Gd7_5h_expr.txt","w")
Toll9_3h=open("output/Toll9_3h_expr.txt","w")
Toll9_5h=open("output/Toll9_5h_expr.txt","w")
Toll10b_3h=open("output/Toll10b_3h_expr.txt","w")
Toll10b_5h=open("output/Toll10b_5h_expr.txt","w")
for line in f.readlines():
	line=line.strip("\n").split(" ")
	line[0]=line[0].replace('"', '')
	Gd7_3h.write(f'{line[0]}\t{line[1]}\n')
	Gd7_5h.write(f'{line[0]}\t{line[2]}\n')
	Toll9_3h.write(f'{line[0]}\t{line[5]}\n')
	Toll9_5h.write(f'{line[0]}\t{line[6]}\n')
	Toll10b_3h.write(f'{line[0]}\t{line[3]}\n')
	Toll10b_5h.write(f'{line[0]}\t{line[4]}\n')