---
title: "verify_IM_PET"
output: html_document

params:
  workingDir: ~/Applied_Bioinformatics_Group_4/
  RscriptsDir: script/original_scripts/
  resultsDir: IM-PET/
  resultsFile: Predictions.txt
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(paste(params$workingDir, params$RscriptsDir,"ExpressionAnalysisFunctions.r", sep = ""))

```

## Verification of IM-PET

```{r load data}
resultsFilePath =paste(params$workingDir, params$resultsDir, params$resultsFile, sep = "")
results = read.table( file = resultsFilePath, header = TRUE, 
                     sep = "\t", quote = "",  
                     stringsAsFactors = FALSE)
```

## ROC
```{r roc analysis  , include=FALSE}
results$Score = as.numeric(results$Score)

resultsGood = results %>% filter(Score > 0.7)
resultsBad = results %>% filter(Score <= 0.7)

resultsGood$IM_Pet = rep(1, times = nrow(resultsGood))
resultsBad$IM_Pet = rep(0, times = nrow(resultsBad))

resultsAll = rbind(resultsGood, resultsBad)


d1ROCi = getROCinfo(resultsAll,scoreColumn = "Score", classColumn = "IM_Pet")
d2ROCi = getROCinfo(resultsAll,scoreColumn = "distance2", classColumn = "inSitu")



ROCplotInfo = rbind (d1ROCi$ROCplotInfo)
ROCplotSummary = rbind(d1ROCi$Youden)


```

```{r plot ROC}

ROCplotSummary

qplot(PC, Variance, data=e.var, geom = c("point")
      , ylim = c(0,max(e.var$Variance)+5)
      ,ylab = "Variance (%)")


ggplot(ROCplotInfo, mapping =  aes(x = FPR, y = TPR, color = score))+
  geom_line()+
  geom_abline()+
  geom_point(data = ROCplotSummary, mapping = aes(y = TPR, x = FPR, color = score ), size = 4) +
    facet_grid(.~classifier)

```
