---
title: "ChIPseq analysis"
author: "Johan"
date: "10/25/2019"
output: html_document

params:
  workingDir: /Users/johanreimegard/git/flyEmbryogenesis
  RscriptsDir: R_Analysis/Rscripts  
  dataDir: data/ChIPseq
  sampleInfo: information/ChIP_ATAC_sampleInfo.tab.txt
  count_K27ac: K27ac.featureCount.count.tab.txt 
  count_K27me3: K27me3.featureCount.count.tab.txt
  count_H3K4me1: H3K4me1.featureCount.count.tab.txt 
  count_zld: zld.featureCount.count.tab.txt

  RfunctionsDirectory: /Users/johanreimegard/GoogleDrive/git/RNAmappingPipeline/R
  
  
---

```{r setup, include=FALSE}

source(paste(params$RfunctionsDirectory,"ExpressionAnalysisFunctions.R",sep = "/"))
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

library(gplots)

library(knitr)
#install.packages("kableExtra")
library(kableExtra)



```

# ChIPseq analysis


## Reads mapping


## Comparing mapping pattern between the samples

### Using feature count to get the difference between the samples

```{r Adding the first analysis of the data}
# install RColorBrewer if missing
if (!require("RColorBrewer")) {
    install.packages("RColorBrewer")
}
library(RColorBrewer)
library(gplots)
featureCountFile = paste(params$workingDir, params$dataDir,params$count_K27me3, sep = "/")

FCdata = read.table( file = featureCountFile, header = TRUE, 
                     sep = "\t", quote = "",  
                     stringsAsFactors = FALSE)

peakInfo  = FCdata [,1:6]
countData = FCdata[,-1:-6]
rownames(countData) = geneInfo$Geneid

colnames(countData)
```


```{r handle the samples}

sampleInfoFile =paste(params$workingDir, params$sampleInfo, sep = "/")
sampleInfo = read.table( file = sampleInfoFile, header = TRUE, 
                     sep = "\t", quote = "",  
                     stringsAsFactors = FALSE)


sampleInfo$bamFiles2  =  gsub(pattern = "/",replacement = ".",x = sampleInfo$bamFiles)
sampleInfo$bamFiles2  =  gsub(pattern = "-",replacement = ".",x = sampleInfo$bamFiles2)


sampleInfoCountTable = data.frame(bamFiles2 = colnames(countData))


sampleInfo = inner_join(sampleInfo,sampleInfoCountTable)

countData = countData[,sampleInfo$bamFiles2]
colnames(countData) = sampleInfo$SampleInfo

```




```{r first qc analysis}

geneExpression = log(rowSums(countData))

hist(geneExpression)

geneInfo$expression  =log(rowSums(countData))

geneInfo.QC = geneInfo %>% filter(expression > 1) 
countData.QC =  countData[geneInfo.QC$Geneid,]

distance = cor((countData.QC))

distance_matrix <- as.matrix(distance)
heatmap.2(distance_matrix, 
              col=brewer.pal(9,"Blues"), 
              density.info = "none",
              trace="none")


```

```{ }
system R failed: 256 at /proj/snic2019-30-14/private/perl/NRSA-v2/bin/pause_PROseq.pl line 426.

```