---
title: "PROseq analysis"
author: "Johan"
date: "10/25/2019"
output: html_document

params:
  workingDir: /Users/johanreimegard/git/Applied_Bioinformatics_Group_4
  dataDir: data/PROseq
  RfunctionsDirectory: 
  proSeqDir: results/PROseq
  proSeq.data: PROseq.data.tsv
  rerun: FALSE

---



```{r setup, include=FALSE}
source(paste(params$workingDir,"Rscripts/ExpressionAnalysisFunctions.R",sep = "/"))



library(dplyr)
library(tidyr)
library(ggplot2)

library(knitr)
#install.packages("kableExtra")
library(kableExtra)


##install.packages("viridis")  # Install
library("viridis")     

knitr::opts_chunk$set(echo = TRUE)

```

# PROseq analysis

## Pre QC analysis


```{r  add fastqc}

# Load in the fastq file that is generated as data from running multiqc on all samples. 
fastqcFile = paste(params$workingDir, params$dataDir,"multiqc_fastqc.txt", sep = "/")
fastqc = read.table(file = fastqcFile, header = T, sep = "\t")


# Use only some of the columns .
fastqc_info = fastqc %>% dplyr::select(Sample,avg_sequence_length,Total.Sequences )

# Spread the data from idxSummary agains so that each species gets its own column 
sampleInfo =   idxSummary %>% dplyr::select(species, Sample, TotalCount) %>% spread(key = species, value = TotalCount)

# Join idx stats and fastqc stats 
sampleInfo = inner_join(sampleInfo,fastqc_info) 

# Nr unmapped by subtraction
unmapped  = sampleInfo %>% dplyr::group_by(Sample) %>% dplyr::summarize(unmapped = Total.Sequences-Drosophila-Mouse)
sampleInfo = inner_join(sampleInfo,unmapped)


# Plot the data in a html format table. 


sampleInfo %>% dplyr::select(Sample,avg_sequence_length,Total.Sequences,Drosophila,Mouse,unmapped) %>%
  kable() %>%
  kable_styling()


```


### Comparing mapping pattern between the samples


```{r Load the data, include=FALSE }
# install RColorBrewer if missing
#if (!require("RColorBrewer")) {
#  install.packages("RColorBrewer")
#}
library(RColorBrewer)
library(gplots)
featureCountFile = paste(params$workingDir, params$dataDir,"counts.CDS.txt", sep = "/")

FCdata = read.table( file = featureCountFile, header = TRUE, 
                     sep = "\t", quote = "",  
                     stringsAsFactors = FALSE)

geneInfo  = FCdata [,1:6]
geneInfo  = geneInfo[,c(1,6)]
countData = FCdata[,-1:-6]
rownames(countData) = geneInfo$Geneid
```


```{r Create meta data table for samples , include=FALSE}

sampleInfoOld = sampleInfo
sampleInfo = data.frame(bamFile =  colnames(countData))
sampleInfo= sampleInfo %>% separate(col = bamFile,sep = "\\.",into =  c("dir", "mutant","sampleInfo"), remove = FALSE)
sampleInfo = sampleInfo %>% separate(col = sampleInfo,sep = "_",into =  c("irrelevant", "time","replicate"))

sampleInfo = sampleInfo %>% separate(col = mutant,sep = "_",into =  c("mutant"))

sampleInfo = sampleInfo %>% dplyr::select(bamFile,mutant,time,replicate)
sampleInfo = sampleInfo %>% unite("sampleName", mutant:time:replicate, remove = FALSE )
sampleInfo = sampleInfo %>% dplyr::select(bamFile,sampleName,mutant,time,replicate)


rownames(sampleInfo) = sampleInfo$bamFile
sampleInfo = sampleInfo[colnames(countData), ]
colnames(countData) = sampleInfo$sampleName
rownames(sampleInfo) = sampleInfo$sampleName

sampleInfo = sampleInfo %>% dplyr::select(sampleName,mutant,time,replicate,bamFile)



```


```{r first qc analysis}

geneExpression = log(rowSums(countData))

hist(geneExpression)

geneInfo$expression  =log(rowSums(countData))

geneInfo.QC = geneInfo %>% filter(expression > 1) 
countData.QC =  countData[geneInfo.QC$Geneid,]

distance = cor((countData.QC))

distance_matrix <- as.matrix(distance)
heatmap.2(distance_matrix, 
          col=brewer.pal(9,"Blues"), 
          density.info = "none",
          trace="none")


```


```{r script to check the known genes. }

knownGenes = read.table(file = paste(params$workingDir,"information/FlyBase_IDs.txt", sep = "/"),
                        sep = "\t", header = F, quote = "", stringsAsFactors = F)
colnames(knownGenes) = c("Submitted ID", "Current ID","Converted ID","Related record")

roshanGenes = read.table(file = paste(params$workingDir,"information/PROseq_DEG_IGB_validated.txt", sep = "/"),
                         sep = "\t", header = T, quote = "", stringsAsFactors = F)
colnames(roshanGenes) = c("SYMBOL", "Mutant")


geneInfo.QC$knownGene = "No"
geneInfo.QC$knownGene[geneInfo.QC$Geneid %in% knownGenes$`Current ID`] = "Yes"

table(geneInfo.QC$knownGene)

countData.QC.knownTargets =  countData[geneInfo.QC$Geneid[geneInfo.QC$knownGene == "Yes"],]
distance = cor((countData.QC.knownTargets))

distance_matrix <- as.matrix(distance)
pdf(file = "PROseqData.HeatMap.knownGenes.pdf")
heatmap.2(distance_matrix, 
          col=brewer.pal(9,"Blues"), 
          margins = c(8, 8),
          density.info = "none",
          trace="none")

dev.off()


```


#### Identifying that two samples have wrong lables and needs to be switched.
```{r change the two files that differ}
# Change filenames 
test = sampleInfo["toll10b_5h_rep1", ]
sampleInfo["toll10b_5h_rep1", ] = sampleInfo["gd7_5h_rep1", ]  
sampleInfo["gd7_5h_rep1", ] = test 
colnames(countData) = sampleInfo$sampleName
rownames(sampleInfo) = sampleInfo$sampleName
countData.QC =  countData[geneInfo.QC$Geneid,]

countData.QC.knownTargets =  countData[geneInfo.QC$Geneid[geneInfo.QC$knownGene == "Yes"],]
distance = cor((countData.QC.knownTargets))

distance_matrix <- as.matrix(distance)


pdf(file = "PROseqData.HeatMap.knownGenes.pdf")
heatmap.2(distance_matrix, 
          col=brewer.pal(9,"Blues"), 
          margins = c(8, 8),
          density.info = "none",
          trace="none")

dev.off()



```

## Differentiall expresssion analysis

###Normalising data and removinvg lowly expressed genes


```{r differential gene expression analysis}
library(DESeq2)

exp.data = countData.QC
metaInfo = sampleInfo


metaInfo$mutant = as.factor(metaInfo$mutant)
metaInfo$time = as.factor(metaInfo$time)

dds <- DESeqDataSetFromMatrix(countData = exp.data,
                              colData = metaInfo,
                              design = ~time + mutant )


#Remove rows with low counts and normalise samples for visualisation
dds <- dds[ rowSums(counts(dds)) > 100, ]

dim(dds)
#Normalizing and change to 2 fold log changes. 
rld <- rlog(dds)

normExpression = as.data.frame(assay(rld))
head(normExpression)

normExpression$geneID = rownames(normExpression)
normExpressionDF  = normExpression %>% gather( key = sampleName, value = rlog, -geneID)

normExpressionDF = inner_join(normExpressionDF, sampleInfo)


ggplot(normExpressionDF, aes(x = rlog, color = sampleName, linetype = time)) + geom_density()

geneInfo = normExpressionDF %>% dplyr::select(geneID, rlog, sampleName) %>% 
  dplyr::group_by (geneID) %>%
  dplyr::summarize ( min = min(rlog), max = max(rlog), mean = mean(rlog), sd = sd(rlog), overQC = length(which(rlog > 5)) ) 
geneInfo.QC2 = geneInfo %>% filter(overQC > 2)
normExpressionDF.QC = normExpressionDF %>% filter(geneID %in% geneInfo.QC2$geneID)

ggplot(normExpressionDF.QC, aes(x = rlog, color = mutant, linetype = time)) + geom_density()


normExpression.QC = normExpressionDF.QC %>%
  dplyr::select(geneID, sampleName, rlog) %>% 
  spread(key = sampleName, value = rlog)


rownames(normExpression.QC) = normExpression.QC$geneID
normExpression.QC = normExpression.QC[, -1]



```


### Visualising the data
```{r heatmap of samples}

#+ save1, include=FALSE
#png(paste(params$workingDirectory, params$proSeqDirectory,"SampleDistance.png", sep = "/"))
#plotSample2SampleDistance(assay(rld))
#dev.off()

#' 
#'
plotSample2SampleDistance(normExpression.QC)
#'  __Figure 1 Plotting sample to sample distance__ . 
#'  0 means that they are identical and 1 means that they are totally different.  
#'  The darker the blue the more similair. Also dendogram shows how similair they are. 
#' 
#' Samples do not cluster according to pre an post op. Most likely more due to difference in mapping (technical problem)
#' 
#' #### PCA analysis
#' Running PCA on the samples and plotting the different variables to see which of the parameterrs that fit the different components the best.
#' 
#' First checking how much the different PC contribute. 

```

###PCA analysis with normalised counts

```{r PCA analysis}

mir.pca <- prcomp(t(normExpression.QC), center = TRUE, scale = FALSE) 
e.var = (mir.pca[['sdev']]^2 / sum(mir.pca[['sdev']]^2))
e.var = as.data.frame( e.var )
e.var$PC = as.factor(1:nrow(e.var)) 
e.var$Variance = e.var$e.var*100
e.var$CumulativeVariance = cumsum(e.var$Variance)
qplot(PC, Variance, data=e.var, geom = c("point")
      , ylim = c(0,max(e.var$Variance)+5) 
      ,ylab = "Variance (%)")

#'  __Figure 2 Plotting PCA variance__.  
#'  Displays how much each of the PC contributes to the overall expression.    
#'  This suggest that the two first PC explains most of the variation.
#'
#+ save2, include=FALSE
#ggsave(paste(params$workingDirectory,params$proSeqDirectory, "PCAvariance.png", sep = "/"))
#'
#'
pctable = as.data.frame(mir.pca$x)[, 1:6]
pctable$sampleName = rownames(pctable)
pctable = inner_join(pctable, metaInfo)


test  = plotPCAplot(PCAinfo = pctable, n.comp = 5,
                    varianceInfo = e.var, 
                    colorComponent = "mutant", 
                    pchComponent = "time"
)
test
#ggsave("PCA_analysis.pdf")


ggplot(data = pctable, mapping = aes(x = PC1, y =  PC3, color = mutant)) + geom_point()

ggplot(data = pctable, mapping = aes(x = PC2, y =  PC5, color = mutant, shape = time)) + geom_point(aes(shape=time))

loadings = mir.pca$rotation[,1:3]


mean = pctable %>% dplyr::select(PC1,PC2,PC3,mutant) %>%
  dplyr::group_by(mutant) %>%
  dplyr::summarise(PC1 = mean(PC1) ,PC2 = mean(PC2), PC3 = mean(PC3) )

meantime = pctable %>% dplyr::select(PC1,PC2,PC3,time) %>%
  dplyr::group_by(time) %>%
  dplyr::summarise(PC1 = mean(PC1) ,PC2 = mean(PC2), PC3 = mean(PC3) )


origo = data.frame(PC1=0, PC2 = 0, PC3 = 0)


line.gd7 = rbind(mean[1,2:4],origo,-mean[1,2:4])
line.gd7$factor = "Gd7"
line.toll10b = rbind(mean[2,2:4],origo,-mean[2,2:4])
line.toll10b$factor = "Toll10b"
line.toll9 = rbind(mean[3,2:4],origo,-mean[3,2:4])
line.toll9$factor = "Toll9"
line.time = rbind(meantime[2,2:4],origo,meantime[1,2:4])
line.time$factor = "Time"


line = rbind(line.gd7,line.toll10b,line.toll9,line.time)


pctable$factor  = pctable$mutant
pctable$factor =  recode(pctable$factor, gd7 = "Gd7")
pctable$factor =  recode(pctable$factor, toll9 = "Toll9")
pctable$factor =  recode(pctable$factor, toll10b = "Toll10b")


fileNameFigCDSsamples = paste( params$workingDir, params$proSeqDir, 
                        paste("PCA_samples_with_decisionlines_CDS.pdf", sep = "_") ,
                        sep = "/")
ggplot(line, mapping = aes(x = PC2,y = PC3, color = factor))+ geom_line() + geom_point(data = pctable,  mapping = aes(x = PC2,y = PC3, color = factor, shape = time))+
  scale_color_viridis(discrete = TRUE, option = "D")
ggsave(fileNameFigCDSsamples)
```


```{r Plot the axis }

qplot(PC, Variance, data=e.var, geom = c("point")
      , ylim = c(0,max(e.var$Variance)+5) 
      ,ylab = "Variance (%)")

test
fileNameFigCDSsamples = paste( params$workingDir, params$proSeqDir, 
                        paste("PCA_samples_with_decisionlines_CDS.pdf", sep = "_") ,
                        sep = "/")
ggplot(line, mapping = aes(x = PC2,y = PC3, color = factor))+ geom_line() + geom_point(data = pctable,  mapping = aes(x = PC2,y = PC3, color = factor, shape = time))+
  scale_color_viridis(discrete = TRUE, option = "D")
ggsave(fileNameFigCDSsamples)

ggplot(line, mapping = aes(x = PC1,y = PC2, color = factor))+ geom_line() + geom_point(data = pctable,  mapping = aes(x = PC1,y = PC2, color = factor, shape = time))+
  scale_color_viridis(discrete = TRUE, option = "D")
```



### Print PROseq data to file 

```{r visualise all individual genes2}

PROseq.data.print  = PROseq.data

PROseq.data.print =  PROseq.data.print %>% dplyr::select(-Mutant)


fileNamePROseq = paste( params$workingDir, params$proSeqDir,  
                        params$proSeq.data,
                             sep = "/")
write.table(x = PROseq.data.print, file = fileNamePROseq,
                  quote = F, sep = "\t", col.names = T, row.names = F) 
      
PROseq.data.selected  = PROseq.data %>%filter (annotation2 == "DE") %>%dplyr::select(geneID,transcriptID, factor,direction) %>% distinct()



write.table(x = PROseq.data.selected, 
            file = paste( params$workingDir, params$proSeqDir, 
                          "selectedGenes.tsv" ,sep = "/"),
            quote = F, sep = "\t", col.names = TRUE, row.names = F)  



```










```{ }
system R failed: 256 at /proj/snic2019-30-14/private/perl/NRSA-v2/bin/pause_PROseq.pl line 426.

```