---
title: "Adding annotation"
author: "Jenny Jakobsson"
date: "12/3/2020"
output: html_document

params:
  workingDir: ~/Applied_Bioinformatics_Group_4/
  resultsDir: results/altered_method/pairs/
  functionAnnotation: hgTables.txt
  pairs15kb: EGP_PCA_filtering.tsv
  resultsAnnotated15kb: annotated_results15kb.txt
  resultsAnnotatedCleaned15kb: annotated_cleaned_results15kb.txt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
library(clusterProfiler)
library(org.Dm.eg.db)
```

```{r }
# Load the ATAC seq loading scores
annotation_data = read.table(
  file = paste(params$workingDir, params$functionAnnotation, sep = ""),
  quote = "",
  sep = "\t",
  header = TRUE,
  stringsAsFactors = F
)
pairs = read.table(
  file = paste(params$workingDir, params$resultsDir, params$pairs15kb, sep = ""),
  quote = "",
  sep = "\t",
  header = TRUE,
  stringsAsFactors = F
)
annotation_data_cleaned = annotation_data %>% dplyr::select(acc, protFullNames, score, geneName, functionText)
annotation_data_cleaned = annotation_data_cleaned %>% dplyr::rename(name = acc,
                                                                    geneFunc = protFullNames,
                                                                    geneFuncFullText = functionText)

# Needs a name to match the annotation files
pairs_cleaned = pairs %>% dplyr::select(EnhancerID, Gene_geneID)
universe <- bitr(
  unique(pairs_cleaned$Gene_geneID),
  fromType = "ENSEMBL",
  toType = c("UNIPROT"),
  OrgDb = org.Dm.eg.db
)
universe  =  universe %>% dplyr::rename(Gene_geneID = ENSEMBL, name = UNIPROT)

# Join the uniprot names with the Ensembl IDs
pairs_uniprotID = inner_join(pairs, universe, by = "Gene_geneID")
# Now join the pairs with the annotation from SwissProtUniprot
AllData = inner_join(pairs_uniprotID, annotation_data_cleaned, by = "name")

# Make the results cleaner for output. One file with less information for easier overview
AllData_renamed = AllData %>% dplyr::rename(
  UNIPROTname = name,
  Enhancer_Chr = Chr,
  Enhancer_Start = ATAC_Start,
  Enhancer_End = ATAC_End
)
AllData_cleaned = AllData_renamed %>% dplyr::select(
  EnhancerID,
  Gene_geneID,
  EnhancerDistance,
  PROseq_Classification,
  ATACseq_Classification,
  UNIPROTname,
  geneFunc,
  geneName,
  geneFuncFullText
)
# The more complete result file
results = paste(params$workingDir,
                params$resultsDir,
                params$resultsAnnotated15kb ,
                sep = "")
write.table(
  x = AllData,
  file = results,
  quote = F,
  sep = "\t",
  row.names = F,
  col.names = T
)
# The result file with better overview
results_cleaned = paste(params$workingDir,
                               params$resultsDir,
                               params$resultsAnnotatedCleaned15kb ,
                               sep = "")
write.table(
  x = AllData_cleaned,
  file = results_cleaned,
  quote = F,
  sep = "\t",
  row.names = F,
  col.names = T
)

```
